# Generated by Django 5.2.1 on 2025-05-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='box',
            name='nombre',
        ),
        migrations.AddField(
            model_name='box',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='box',
            name='numero',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
