# Generated by Django 5.2.1 on 2025-05-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_box_disponible_remove_doctor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
